### ISSUE TITLE
Adding a new properties to the Entities Object "ingoreInSwagger"

### ISSUE THREAD

**Issue by snowVolleyball** [Kull-AG/kull-generic-backend#6]
current all Entities are show in Swagger, but may some we only like to use in a local controller.
May in relation to the #5 it's possible to add a new property where we can put all 

in the case there is the flag IgnorinSwagger set, the content is changing as there is no longer a need for the HTTP verb. It's enough to have "only" the sp name.

example:
 "EntitiesGroups": [
    {
      "GroupName": "login",
      "Entities": {
        "login": {
          "Get": "login.sprDoLogin"
        }
      }
    },
    {
      "GroupName": "internalOnly",
      "IgnoreInSwagger": true,
      "Methods": [
        "login.getAllDataForAnUser"
      ]
    }
  ],

**Comment by aersam** [comment]
I'll close this one as this use case is covered in DbAccessCodeGen Projects, whose config is very similar: https://github.com/aersamkull/DbAccessCodeGen
